### ISSUE TITLE
with ion-nav

### ISSUE THREAD

**Issue by vinodhum** [mburger81/ionic2-angular2-router#1]
how do you use this with ion-nav ?
I tried 
<ion-nav main [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>
but its not working

**Comment by mburger81** [comment]
You can't combine ion-nav with angular 2 router. 
In meantime I don't use angular router anymore in my projects.
I migrate to Ionic's lazy loading which are not baf but stilll have many problems.

**Comment by vinodhum** [comment]
I tied lazy loading but having hard time to import custom component.
Thanx
